# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zyboz7_pins.xdc

# Block Designs: bd/spi_com/spi_com.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_com || ORIG_REF_NAME==spi_com} -quiet] -quiet

# IP: bd/spi_com/ip/spi_com_processing_system7_0_0/spi_com_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_com_processing_system7_0_0 || ORIG_REF_NAME==spi_com_processing_system7_0_0} -quiet] -quiet

# IP: bd/spi_com/ip/spi_com_spi_logic_0_0/spi_com_spi_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==spi_com_spi_logic_0_0 || ORIG_REF_NAME==spi_com_spi_logic_0_0} -quiet] -quiet

# XDC: c:/Users/gdela/spi_com_1/spi_com_1.gen/sources_1/bd/spi_com/spi_com_ooc.xdc
