# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gdela/spi_com_1/spi_com_1.srcs/sources_1/bd/spi_com/ip/spi_com_processing_system7_0_0/spi_com_processing_system7_0_0.xci
# IP: The module: 'spi_com_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gdela/spi_com_1/spi_com_1.gen/sources_1/bd/spi_com/ip/spi_com_processing_system7_0_0/spi_com_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_com_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/gdela/spi_com_1/spi_com_1.srcs/sources_1/bd/spi_com/ip/spi_com_processing_system7_0_0/spi_com_processing_system7_0_0.xci
# IP: The module: 'spi_com_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gdela/spi_com_1/spi_com_1.gen/sources_1/bd/spi_com/ip/spi_com_processing_system7_0_0/spi_com_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'spi_com_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
